### ISSUE TITLE
Identifying Slices - Complete the documentation

### ISSUE THREAD

**Issue by michaelpiron** [project-origin/registry#108]
### Discussed in https://github.com/orgs/project-origin/discussions/19

<div type='discussions-op-text'>

<sup>Originally posted by **michaelpiron** April 25, 2023</sup>
From the Project Origin registry documentation, I deduce that Slices don't have an unique identifier within the registry.

For example:
The command to **slice up a Slice**:
[API -> ProjectOrigin.Electricity.Client.ElectricityCommandBuilder -> SliceCertificate command](https://project-origin.github.io/registry/api/ProjectOrigin.Electricity.Client.ElectricityCommandBuilder.html#ProjectOrigin_Electricity_Client_ElectricityCommandBuilder_SliceCertificate_ProjectOrigin_Electricity_Client_Models_FederatedCertifcateId_ProjectOrigin_Electricity_Client_Models_SliceCollection_Key_)
We address the Slice by specifying:
* **Certificate ID** --> the unique ID of the parent Granular Certificate above the Slice
* **Key** --> signing key of the current owner of the Slice

The same structure is used for the commands to transfer Slices, and to claim Slices.

However, underneath a given Granular Certificate, you might have multiple Slices owned by a single owner. How does the command know which Slice to slice up exactly?
Shouldn't Slices have their own unique ID by which they can be addressed?

@wisbech @MartinSchmidt </div>

@MartinSchmidt 's answer was very clarifying, and would be a great addition in the documentation:
>  a slice does have a unique value the commitment. This is used to identify slices, as they are a result of the amount (Wh) and the random value. Commitments of equal size would still have different commitments. And if you find an easy way to find amounts and random values with the same commitment, then we would have a general issue using Pedersen Commitments, as it is part of the math that it is a hard problem to solve.
  
>  We chose to use the commitment instead of introducing another ID, simple to save on space and bandwith, and it would give no benefit as we saw it.
  
>  I hope this answers the question, and a possibly great addition to the documentation.
  
>  On a side note, even if the slices was owned by the same entity, I would still recommend using different key-pairs as to hide the fact it is the same owner, and using protocols as bip32, it would be trivia.

**Comment by MartinSchmidt** [comment]
@michaelpiron [We added](https://project-origin.github.io/registry/concept/granular-certificates/readme.html#slices) it a couple of days ago #107, do you think this is sufficient, or do you think it should be further explained in the doc?

**Comment by michaelpiron** [comment]
@MartinSchmidt sorry I missed that update. Update in the documentation seems good.
Detailed comment: perhaps links to Github discussions should be avoided, in order to keep the documentation as self-standing as possible?
Thx

**Comment by wisbech** [comment]
I do think that the causation of a decision is of great importance, hence it impedes circular argumentation - so I see no problem of having a free and less formal discussion forum where derived arguments and insights are being added to the RFC ADR and what not. 

BTW @michaelpiron great to see your engagement in the async forum, it is how it should work in an open source context 👍
