### ISSUE TITLE
🐞 [BUG] - Unable to load shared library 'rust_ffi'

### ISSUE THREAD

**Issue by GuyHeylens** [project-origin/registry#130]
### Describe the Bug

Trying to run ProjectOrigin.Electricity.Example from MAC returns an error 'Unable to load shared library 'rust_ffi''. 

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'rust_ffi' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/Users/guyheylens/Documents/Coding/registry/src/ProjectOrigin.Electricity.Example/bin/Debug/net7.0/runtimes/osx-arm64/native/rust_ffi.dylib, 0x0001):
```

### To Reproduce

```bash
1. Clone GIT repo to local machine (MacOS)
2. Open repository in Jetbrains Rider 
3. Run Electricity.Example app
...
```

### Expected Behavior

Example app works as expected.

### Desktop

- OS: macOS
- Version Version 13.4.1 

### Additional Context

Ex

**Comment by MartinSchmidt** [comment]
[Fixed in latest release in other repo](https://github.com/project-origin/pedersen-commitment/releases/tag/v1.0.3)
