### ISSUE TITLE
[Assignment] - Zero Knowledge proof and Elliptic curve commitment

### ISSUE THREAD

**Issue by wisbech** [project-origin/registry#21]
A zero-knowledge proof would entatil that the issuer would not have to store the 'm' and 'r' values from the pedersen commitments. This would solve a lot of storage and security issues for the registry operator, and issuer hence it might be worthwhile even at the cost of processing the zero-knowledge proof.

@tpryds are looking into finding the right curve, with the appropriate properties, for zero-knowledge proof and encryption of the pedersen commitments.

**Comment by MartinSchmidt** [comment]
Closed by PR #59
