### ISSUE TITLE
[ Assignment ] - DDOS and other vulnerability checks for the registry

### ISSUE THREAD

**Issue by wisbech** [project-origin/registry#27]
A critical view of the weaknesses of the registry and ways of mitigating known attack vectors from potential malicious actors:

- DDOS
- MITM 
- ...

**Comment by lauranolling** [comment]
I labelled this as `documentation`, as it seems to be what the issue is about given the wording:

> A critical view of...

In the issue's description. Is this correctly understood?

**Comment by MartinSchmidt** [comment]
Not part of the service itself, must be part of the hosting setup.
