### ISSUE TITLE
Create chart and container

### ISSUE THREAD

**Issue by MartinSchmidt** [project-origin/registry#42]
To complete the Alpha release, we need a Helm Chart as a deliverable that allows teams to spin up the alpha-registry.

todo:
- [x] Create a dockerfile for the alpha-server .
- [x] Create workflow to release the docker image when a branch is merged to main.
- [x] Create helm chart.
- [x] Create workflow that publishes the helm chart.

Questions
- How should we do version management? 
- semver?
- Should we use git tags or commit the versions in a file?

**Comment by wisbech** [comment]
Maybe [pulumi](https://www.pulumi.com/docs/intro/vs/k8s-yaml-dsls/) could be a way of setting up this workflow
