### ISSUE TITLE
Running registry instance for starting to use client library

### ISSUE THREAD

**Issue by duizer** [project-origin/registry#69]
The client library needs a running instance of the registry. We are interested in getting to know the library and do not need to have a production-ready instance running; something for local development is what we looking for.  
What are the current possibilities for running an instance or maybe accessing a public available instance? In https://github.com/project-origin/registry/issues/42 a docker image is on the roadmap - is that a possibility?

**Comment by duizer** [comment]
@wisbech, thank you. Did you land on an option for the running instance at the workshop?

**Comment by wisbech** [comment]
As always the issue is [#42 ](https://github.com/project-origin/registry/issues/42) and I am a bit at odds here - if there are any volunteers, hint @duizer, with ninja helm chart deployment skills please say grrr and let us try it out and make it work.

**Comment by duizer** [comment]
Sorry, I am not the helm chart ninja you are looking for.

**Comment by MartinSchmidt** [comment]
@duizer since a helm chart is now available, is this sufficient close this issue?

**Comment by duizer** [comment]
Yes, please close this issue.
