### ISSUE TITLE
Public keys and signing keys

### ISSUE THREAD

**Issue by Exobitt** [project-origin/registry#88]
In your documentation, theres some mentions about public and signing keys we have some questions about.

-  What's the difference between public keys and signing keys?
- Are we bound to the algorithm ED25509?
- Are there any minimum/maximum size of the keys?
- Are public keys immutable?
- How will the registry react, if a public key is switched for the same user?

**Comment by MartinSchmidt** [comment]
Questions should be covered by documentation
