### ISSUE TITLE
🐞 [BUG] - Cannot add package ProjectOrigin.Electricity.Client

### ISSUE THREAD

**Issue by duizer** [project-origin/registry#89]
### Describe the Bug

Running `dotnet add package ProjectOrigin.Electricity.Client --version 0.1.0-alpha.3` results in this error: 

> #7 6.697 error: NU1101: Unable to find package ProjectOrigin.PedersenCommitment. No packages exist with this id in source(s): nuget.org

Navigating to https://www.nuget.org/packages/ProjectOrigin.PedersenCommitment/ returns 404 NotFound.

### To Reproduce

Try to build this Dockerfile:

```
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /src

RUN dotnet new console
RUN dotnet add package ProjectOrigin.Electricity.Client --version 0.1.0-alpha.3

ENTRYPOINT [ "dotnet", "run" ]
```

### Expected Behavior

Package is added

### Desktop

See Dockerfile in "To Reproduce"

**Comment by wisbech** [comment]
Hi @duizer - maybe with the work from @guidmaster this should work. I will try and replicate the above bug, but there where some significant work done on a #47 that might cover this issue. It is a hail mary and if it works great otherwise I will look into it first thing next week.
