### ISSUE TITLE
🐞 [BUG] - Github workflows/concordium-integration-tests fails

### ISSUE THREAD

**Issue by wisbech** [project-origin/registry#91]
### Describe the Bug

The concordium-integrations-tests fails everytime the action is run. We have to address this - I will ask @MartinSchmidt for some insights here - apperantly the workflow times out which might be due to changes in the underlying API since the initial commits that worked. I will look into it myself as well.

### To Reproduce

```bash
1.Make a PR on any branch
2. Trigger workflows
3. Get an error on workflows/concordium-integration-tests
...
```

### Expected Behavior

Green flags through and throguh

### Screenshots

![image](https://user-images.githubusercontent.com/3016694/222744819-eee5d871-a16f-4699-a669-cc6044bec0c5.png)

### Desktop

- OS: [OSX]
- Version [12.5.1]
- Browser [chrome, vscode]

**Comment by MartinSchmidt** [comment]
Solved.
